In [ ]:
import numpy as np

temperatures_celsius = np.array([22, 24, 19, 21, 23, 25, 26, 27, 24, 23, 20, 22, 21, 19, 18, 22, 23, 24, 26, 28, 30, 27, 25, 26, 24, 22, 21, 20, 19, 23])

min_temp = np.min(temperatures_celsius)
max_temp = np.max(temperatures_celsius)
avg_temp = np.mean(temperatures_celsius)

print("Minimum Temperature:", min_temp)
print("Maximum Temperature:", max_temp)
print("Average Temperature:", avg_temp)

temperatures_fahrenheit = (temperatures_celsius * 9/5) + 32
print("Temperatures in Fahrenheit:", temperatures_fahrenheit)

above_25 = temperatures_celsius[temperatures_celsius > 25]
print("Days with temperature above 25°C:", above_25)

below_20_count = np.sum(temperatures_celsius < 20)
print("Number of days with temperature below 20°C:", below_20_count)

sorted_temperatures = np.sort(temperatures_celsius)
print("Sorted Temperatures:", sorted_temperatures)

reshaped_temperatures = temperatures_celsius.reshape(5, 6)
print("Reshaped Temperature Array (5 weeks, 6 days each):\n", reshaped_temperatures)


Minimum Temperature: 18
Maximum Temperature: 30
Average Temperature: 23.133333333333333
Temperatures in Fahrenheit: [71.6 75.2 66.2 69.8 73.4 77.  78.8 80.6 75.2 73.4 68.  71.6 69.8 66.2
 64.4 71.6 73.4 75.2 78.8 82.4 86.  80.6 77.  78.8 75.2 71.6 69.8 68.
 66.2 73.4]
Days with temperature above 25°C: [26 27 26 28 30 27 26]
Number of days with temperature below 20°C: 4
Sorted Temperatures: [18 19 19 19 20 20 21 21 21 22 22 22 22 23 23 23 23 24 24 24 24 25 25 26
 26 26 27 27 28 30]
Reshaped Temperature Array (5 weeks, 6 days each):
 [[22 24 19 21 23 25]
 [26 27 24 23 20 22]
 [21 19 18 22 23 24]
 [26 28 30 27 25 26]
 [24 22 21 20 19 23]]
